on: push
name: Deploy website on push
jobs:
  web-deploy:
  name: Deploy
  runs-on: ubuntu-latest
  steps:
  - name: Get lates code
    uses: actions/checkout@v3

  - name: Sync files
    uses: SamKirkland/FTP-Deploy-Action@4.3.4
    with:
      server: shimacitraselaras.co.id
      username: ${{ secrets.FTPUSERNAME }}
      password: ${{ secrets.FTPPASSWORD }}
      protocol: ftp
      server-dir: public_html/wmanalys.shimacitraselaras.co.id/
